version: '3.3'
services:

  database:
    image: "postgres"
    env_file:
      - ./env/database.env
    volumes:
      - postgres:/var/lib/postgresql/data/
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin:/var/log/data
    ports:
      - 5050:80
    env_file:
      - ./env/pgadmin.env
    depends_on:
      - database
    restart: always 

  backend:
    build: ./backend
    ports:
      - 8080:80
    depends_on:
      - database
    restart: always 

volumes:
  postgres:
  pgadmin:
